export type Locale = "zh" | "en";

const en = {
  meta: { title: "JCL.AI — AI Full-Stack Engineer", description: "Jiang Chaolong’s portfolio: agentic RAG, multimodal AI, real-time intelligent systems and full-stack product engineering." },
  nav: { label: "Main navigation", home: "JCL.AI home", signatureHome: "atchaolong home", skip: "Skip to selected work", items: ["WORK", "ABOUT", "STACK", "LOG"], contact: "LET’S TALK", language: "Language", replay: "Replay opening" },
  hero: { name: "JIANG CHAOLONG", role: "AI ENGINEER", title: ["Making", "intelligence", "work"], statement: "Turning AI potential into products people can use.", sub: "From first principle to final deployment.", action: "EXPLORE MY WORK", tags: ["AI SYSTEMS", "FULL-STACK", "PRODUCT"], location: "BASED IN CHENGDU, CN", scroll: "SCROLL TO DISCOVER", note: "INDEPENDENT MIND. CONNECTED SYSTEMS.", strip: ["AGENTIC SYSTEMS", "MULTIMODAL AI", "REAL-TIME INFRA", "PRODUCT ENGINEERING"] },
  work: { label: "01 / SELECTED WORK", meta: "FOUR SYSTEMS. REAL-WORLD PROBLEMS.", title: ["Ideas are easy.", "I build the rest."], description: "From financial Q&A to real-time speech, connecting models, data and products. Four systems I’ve built.", overview: "architecture overview", system: "SYS", diagram: "ARCHITECTURE STUDY", project: "PROJECT", details: "Explore engineering details", contribution: "MY CONTRIBUTION", flow: "SYSTEM FLOW" },
  projects: [
    { title: "FinsAgent", kicker: "AGENTIC RAG / FINANCE", description: "An agentic RAG question-answering system for finance, connecting planning, retrieval, tool use and verification in a complete loop.", stack: ["LangGraph", "FastAPI", "Vector DB", "Reranker"], role: "AI SYSTEM DESIGN · FULL-STACK", steps: ["PLAN", "RETRIEVE", "ACT", "VERIFY"], parallel: false },
    { title: "Real-time ASR", kicker: "REAL-TIME AI / RTC", description: "Speech recognition, translation and summaries for multi-person meetings, connecting audio capture with live transcription and low-latency delivery.", stack: ["AgoraRTC", "WebSocket", "FunASR", "FastAPI"], role: "REAL-TIME PIPELINE · BACKEND", steps: ["AUDIO", "ASR", "TRANSLATE", "RETURN"], parallel: false },
    { title: "Karavideo", kicker: "MULTIMODAL GENERATION", description: "A multimodal content platform with text-to-video, image-to-video, video tagging, watermark processing and a community gallery.", stack: ["Next.js", "AI APIs", "SEO", "Video"], role: "PRODUCT · FULL-STACK", steps: ["TEXT / IMAGE", "VIDEO"], parallel: false },
    { title: "K12 AI Stack", kicker: "PRODUCT ENGINEERING / 0→1", description: "End-to-end ownership of a K12 product ecosystem, from web and mini programs to administration, databases and deployment for teaching workflows.", stack: ["React", "Node.js", "Mini Program", "Supabase"], role: "0→1 · PRODUCT OWNER", steps: ["WEB", "MINI PROGRAM", "ADMIN"], parallel: true },
  ],
  profile: { label: "02 / ENGINEER PROFILE", meta: "IDENTITY & APPROACH", title: ["I turn AI capability", "into working systems."], paragraphs: ["I’m Jiang Chaolong, an AI full-stack engineer. I care about more than what models can do: I connect models, data, tools, interfaces and infrastructure to make usable products.", "From agentic RAG and real-time speech to multimodal generation, I bridge AI capabilities and practical engineering so ideas can be deployed, tested and used."], tags: ["AI", "FULL-STACK", "SYSTEMS", "PRODUCT"] },
  systems: { label: "SYSTEMS THINKING", title: ["The model is", "only one layer."], description: "An AI product depends on how context, retrieval, tools, state, streaming and infrastructure work together. I make those layers clear, reliable and ready to evolve.", core: "AI CORE", layer: "ORCHESTRATION LAYER", nodes: ["CONTEXT", "TOOLS", "STATE", "STREAM"], tags: ["CONTEXT", "RETRIEVAL", "TOOLS", "STATE", "STREAMING"] },
  stack: { label: "03 / TECHNICAL STACK", meta: "CAPABILITY MAP", title: ["Built across", "the entire stack."], description: "Full-stack means taking an idea all the way from models and APIs to a product in someone’s hands.", groups: ["AI / AGENTS", "AI / ML", "FRONTEND", "BACKEND", "DATA", "INFRASTRUCTURE"], skills: [["LangGraph", "LangChain", "RAG", "Tool Use"], ["PyTorch", "Transformer", "BERT", "YOLO"], ["TypeScript", "React", "Next.js", "Vue"], ["Python", "FastAPI", "Flask", "Node.js"], ["MySQL", "Elasticsearch", "Supabase", "Redis"], ["Docker", "Linux", "CI/CD", "Cloud"]] },
  experience: { label: "04 / SYSTEM LOG", meta: "ENGINEERING HISTORY", title: ["From code", "to systems."], description: "Growing from implementation to systems design, while bringing new AI capabilities into useful products.", rows: [{ year: "2026", title: "Agentic Systems", description: "Focused on agents, RAG, multimodal systems and production AI products." }, { year: "2025", title: "AI Product / Full-Stack", description: "Building financial RAG, real-time ASR, AI video and recruitment projects." }, { year: "2024", title: "Software → Artificial Intelligence", description: "Moving into AI engineering from a solid software foundation." }] },
  contact: { label: "OPEN TO COLLABORATION", title: ["Let’s build something", "intelligent."], description: "Have an ambitious product, an AI system, or a difficult engineering problem?", action: "START A CONVERSATION", copyright: "JIANG CHAOLONG", back: "BACK TO TOP ↑" },
  core: { interact: "Interactive particle character. Click a body part to play; Enter or Space tries a new body trick.", hint: "Hover to meet · tap different parts · hold the body for a hug", tricksLabel: "Try a little trick", tricks: { wink: "Wink", highfive: "High five", dance: "Two-step", spin: "Spin", cuddle: "Hug" }, reactions: { body: "WHAT ARE YOU UP TO?", eyes: "LOOKING AT ME?", nose: "EASY ON THE NOSE…", mouth: "GOT A TUNE?", hands: "UP HIGH?", feet: "SHALL WE DANCE?", wink: "OUR LITTLE SECRET ;)", boop: "BOOP!", highfive: "NAILED IT!", dance: "ONE, TWO. ONE, TWO.", whistle: "♪ JUST VIBING ♪", hop: "A LITTLE HOP!", spin: "TA-DA!", proud: "PRETTY COOL, HUH?", cuddle: "OKAY, ONE LITTLE HUG ♥" }, modes: "Particle shape", orbit: "ORBIT", sphere: "SPHERE", play: "Play particle animation", pause: "Pause particle animation" },
  signature: { label: "Interactive pixel signature", human: "A HUMAN BEHIND THE SYSTEMS", play: "PLAY A LITTLE.", desktop: "MOVE TO DISRUPT · CLICK TO PULSE", touch: "TAP THE LETTERS TO SEND A PULSE", reduced: "BUILT WITH INTENTION.", home: "EVERY PIXEL FINDS ITS WAY HOME.", action: "ATCHAOLONG interactive signature. Click, Enter or Space to send a particle pulse.", static: "ATCHAOLONG pixel signature. Reduced motion enabled." },
  diagram: { play: "Play diagram animation", pause: "Pause diagram animation", sequence: "SEQUENTIAL FLOW", parallel: "PARALLEL SYSTEMS", system: "Context, tools, state and streaming working with the AI core" },
  intro: { tools: ["SEARCH", "MEMORY", "TOOLS", "CODE", "VISION", "CONTEXT"], agent: "AI AGENT", resolved: "THE CONNECTION BECOMES CLEAR", assemble: ["EVERY SIGNAL LEAVES A TRACE", "ONE CONNECTION LEADS TO ANOTHER", "THE PATTERN EMERGES"], assemblyLabel: "TRACING INTELLIGENCE", label: "Portfolio opening", skip: "Skip intro", replay: "Replay intro", line: "IDEAS BECOME SYSTEMS.", caption: "JIANG CHAOLONG / AI ENGINEER", stages: ["CONNECTING IDEAS", "SHAPING INTELLIGENCE", "READY TO BUILD"] },
};
export type Messages = typeof en;
const zh: Messages = {
  meta: { title: "JCL.AI — 蒋朝龙 · AI 全栈工程师", description: "蒋朝龙的个人作品集：智能体检索增强生成、多模态 AI、实时智能系统与全栈产品工程。" },
  nav: { label: "主导航", home: "JCL.AI 首页", signatureHome: "atchaolong 首页", skip: "跳到项目作品", items: ["作品", "关于", "技术栈", "经历"], contact: "聊聊合作", language: "语言", replay: "重播开场" },
  hero: { name: "蒋朝龙", role: "AI 全栈工程师", title: ["让智能", "真正", "落地"], statement: "把 AI 的可能，变成真实可用的产品。", sub: "从底层原理，到产品交付。", action: "探索我的作品", tags: ["智能系统", "全栈开发", "产品工程"], location: "中国 · 成都", scroll: "向下探索", note: "独立思考，让系统彼此连接。", strip: ["智能体系统", "多模态 AI", "实时基础设施", "产品工程"] },
  work: { label: "01 / 精选作品", meta: "四个系统，解决真实问题。", title: ["不止于想法。", "更让它成为现实。"], description: "从金融问答到实时语音，把模型、数据与产品连接起来。这里是我构建的四个系统。", overview: "架构概览", system: "系统", diagram: "架构示意", project: "项目", details: "查看工程细节", contribution: "我的职责", flow: "系统流程" },
  projects: [
    { title: "FinsAgent", kicker: "智能体检索增强 / 金融", description: "面向金融场景的 Agentic RAG 智能问答系统，让任务规划、检索、工具调用与结果验证形成完整闭环。", stack: ["LangGraph", "FastAPI", "向量数据库", "重排序"], role: "AI 系统设计 · 全栈开发", steps: ["规划", "检索", "执行", "验证"], parallel: false },
    { title: "实时语音识别", kicker: "实时 AI / 音视频通信", description: "多人会议语音识别、翻译与摘要系统，贯通音频采集、实时转写、翻译、摘要和低延迟回传。", stack: ["AgoraRTC", "WebSocket", "FunASR", "FastAPI"], role: "实时处理管线 · 后端开发", steps: ["音频", "转写", "翻译", "回传"], parallel: false },
    { title: "Karavideo", kicker: "多模态内容生成", description: "多模态 AI 内容生产平台，覆盖文生视频、图生视频、视频标签、水印处理与内容广场体验。", stack: ["Next.js", "AI 接口", "搜索优化", "视频"], role: "产品设计 · 全栈开发", steps: ["文本 / 图像", "视频"], parallel: false },
    { title: "K12 智能产品体系", kicker: "产品工程 / 从零到一", description: "独立负责 K12 产品体系，从 Web、小程序到后台、数据库和服务器部署，持续支撑真实教学业务。", stack: ["React", "Node.js", "小程序", "Supabase"], role: "从零到一 · 产品负责人", steps: ["网页端", "小程序", "管理后台"], parallel: true },
  ],
  profile: { label: "02 / 关于我", meta: "身份与工作方式", title: ["让 AI 的能力", "成为可用的系统。"], paragraphs: ["我是蒋朝龙，一名 AI 全栈工程师。我关注的不只是模型能做什么，更在意如何把模型、数据、工具、界面与基础设施组合成真正可用的产品。", "从智能体检索增强、实时语音到多模态内容生成，我在抽象智能与真实工程之间搭桥，让想法能够被部署、被验证，也被用户使用。"], tags: ["人工智能", "全栈开发", "系统设计", "产品工程"] },
  systems: { label: "系统思维", title: ["模型，", "只是其中一层。"], description: "真正决定 AI 产品质量的，是上下文、检索、工具、状态、流式输出与工程基础设施如何协同。我的工作，是让每一层都清晰、可靠、可演进。", core: "智能核心", layer: "编排层", nodes: ["上下文", "工具", "状态", "数据流"], tags: ["上下文", "检索", "工具", "状态", "流式输出"] },
  stack: { label: "03 / 技术栈", meta: "能力地图", title: ["贯穿产品的", "每一个技术层。"], description: "全栈不是“什么都懂一点”，而是能把一个想法从模型与 API，一路推进到用户手中。", groups: ["人工智能 / 智能体", "人工智能 / 机器学习", "前端开发", "后端开发", "数据服务", "基础设施"], skills: [["LangGraph", "LangChain", "RAG", "工具调用"], ["PyTorch", "Transformer", "BERT", "YOLO"], ["TypeScript", "React", "Next.js", "Vue"], ["Python", "FastAPI", "Flask", "Node.js"], ["MySQL", "Elasticsearch", "Supabase", "Redis"], ["Docker", "Linux", "持续集成 / 部署", "云服务"]] },
  experience: { label: "04 / 成长记录", meta: "工程经历", title: ["从代码，", "走向系统。"], description: "持续从工程实现走向系统设计，也持续把新的 AI 能力带进可用产品。", rows: [{ year: "2026", title: "智能体系统", description: "聚焦智能体、检索增强、多模态与生产级 AI 产品。" }, { year: "2025", title: "AI 产品 / 全栈开发", description: "金融检索增强、实时语音识别、AI 视频与招聘项目持续落地。" }, { year: "2024", title: "软件工程 → 人工智能", description: "从坚实的软件工程基础进入 AI 工程方向。" }] },
  contact: { label: "期待与你合作", title: ["一起创造", "有用的智能。"], description: "有一个大胆的产品想法、AI 系统，或值得挑战的工程问题？", action: "开启对话", copyright: "蒋朝龙", back: "返回顶部 ↑" },
  core: { interact: "粒子小伙伴，点击不同部位玩耍；Enter 或空格尝试一个身体小动作。", hint: "悬停打招呼 · 点点不同部位 · 按住身体抱一下", tricksLabel: "试个小动作", tricks: { wink: "眨个眼", highfive: "击个掌", dance: "跳两步", spin: "转一圈", cuddle: "抱一下" }, reactions: { body: "你在打什么主意？", eyes: "在看我吗？", nose: "鼻子要轻一点哦…", mouth: "要来一段小曲吗？", hands: "准备击掌？", feet: "一起跳两步？", wink: "这是我们的小秘密 ;)", boop: "啵！", highfive: "默契满分！", dance: "左一下，右一下。", whistle: "♪ 哼一首小曲 ♪", hop: "轻轻蹦一下！", spin: "转完啦，没晕！", proud: "怎么样，我挺酷吧？", cuddle: "好吧，给你抱一下 ♥" }, modes: "粒子形态", orbit: "环形", sphere: "球形", play: "播放粒子动画", pause: "暂停粒子动画" },
  signature: { label: "交互像素签名", human: "系统背后，是一个创造者。", play: "动手试试看。", desktop: "划过打散字形 · 点击释放脉冲", touch: "轻触文字，释放粒子脉冲", reduced: "每一处，皆有用心。", home: "每一个像素，终将归位。", action: "ATCHAOLONG 交互签名，点击或按 Enter、空格释放粒子脉冲", static: "ATCHAOLONG 像素签名，已减少动态效果" },
  diagram: { play: "播放图表动画", pause: "暂停图表动画", sequence: "顺序处理流程", parallel: "并行产品体系", system: "上下文、工具、状态与数据流协同连接智能核心" },
  intro: { tools: ["搜索", "记忆", "工具", "代码", "视觉", "上下文"], agent: "AI 智能体", resolved: "一切，终于相连", assemble: ["每个信号，都留下线索", "循着关联，找到下一条线索", "答案，在联系中浮现"], assemblyLabel: "循迹，见智能", label: "作品集开场", skip: "跳过开场", replay: "重播开场", line: "让想法，成为系统。", caption: "蒋朝龙 / AI 全栈工程师", stages: ["连接想法", "构建智能", "即刻启程"] },
};
export const messages: Record<Locale, Messages> = { zh, en };
